-- ============================================================
-- Academic Backend Database Schema
-- PostgreSQL DDL
-- IDs are generated by the backend or seed process, not by DB defaults.
-- ============================================================

-- ============================================================
-- Enums
-- ============================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'record_status') THEN
    CREATE TYPE record_status AS ENUM ('ACTIVE', 'INACTIVE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_status') THEN
    CREATE TYPE student_status AS ENUM ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'WITHDRAWN', 'GRADUATED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'professor_status') THEN
    CREATE TYPE professor_status AS ENUM ('ACTIVE', 'INACTIVE', 'ON_LEAVE');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'academic_period_status') THEN
    CREATE TYPE academic_period_status AS ENUM ('PLANNED', 'OPEN', 'IN_PROGRESS', 'CLOSED', 'CANCELLED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_offering_status') THEN
    CREATE TYPE course_offering_status AS ENUM ('DRAFT', 'OPEN', 'CLOSED', 'CANCELLED', 'FINISHED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollment_status') THEN
    CREATE TYPE enrollment_status AS ENUM ('PENDING', 'ENROLLED', 'CANCELLED', 'WITHDRAWN', 'REJECTED', 'FINISHED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
    CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'session_status') THEN
    CREATE TYPE session_status AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_status') THEN
    CREATE TYPE import_status AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED');
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'import_row_status') THEN
    CREATE TYPE import_row_status AS ENUM ('ACCEPTED', 'REJECTED', 'DUPLICATED', 'OBSERVED', 'UPDATED');
  END IF;
END
$$;

-- ============================================================
-- Identity and catalogs
-- ============================================================

CREATE TABLE IF NOT EXISTS document_types (
  id UUID PRIMARY KEY,
  code VARCHAR(30) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_document_types_code UNIQUE (code),
  CONSTRAINT uq_document_types_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS persons (
  id UUID PRIMARY KEY,
  document_type_id UUID NOT NULL,
  document_number VARCHAR(30) NOT NULL,
  first_name VARCHAR(120) NOT NULL,
  last_name VARCHAR(120) NOT NULL,
  email VARCHAR(180),
  phone VARCHAR(30),
  birth_date DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_persons_document_type
    FOREIGN KEY (document_type_id)
    REFERENCES document_types (id),

  CONSTRAINT uq_persons_document UNIQUE (document_type_id, document_number)
);

CREATE INDEX IF NOT EXISTS ix_persons_document_number
  ON persons (document_number);

CREATE INDEX IF NOT EXISTS ix_persons_deleted_at
  ON persons (deleted_at);

-- ============================================================
-- Academic structure
-- ============================================================

CREATE TABLE IF NOT EXISTS academic_programs (
  id UUID PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(180) NOT NULL,
  academic_unit VARCHAR(180),
  status record_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_academic_programs_code UNIQUE (code),
  CONSTRAINT uq_academic_programs_name UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS ix_academic_programs_status
  ON academic_programs (status);

CREATE TABLE IF NOT EXISTS course_categories (
  id UUID PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_course_categories_code UNIQUE (code),
  CONSTRAINT uq_course_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS courses (
  id UUID PRIMARY KEY,
  academic_program_id UUID NOT NULL,
  course_category_id UUID,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(180) NOT NULL,
  description TEXT,
  credits INTEGER NOT NULL,
  hours INTEGER,
  status record_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_courses_academic_program
    FOREIGN KEY (academic_program_id)
    REFERENCES academic_programs (id),

  CONSTRAINT fk_courses_course_category
    FOREIGN KEY (course_category_id)
    REFERENCES course_categories (id),

  CONSTRAINT uq_courses_code UNIQUE (code),
  CONSTRAINT ck_courses_credits_positive CHECK (credits > 0),
  CONSTRAINT ck_courses_hours_positive CHECK (hours IS NULL OR hours > 0)
);

CREATE INDEX IF NOT EXISTS ix_courses_academic_program_id
  ON courses (academic_program_id);

CREATE INDEX IF NOT EXISTS ix_courses_course_category_id
  ON courses (course_category_id);

CREATE INDEX IF NOT EXISTS ix_courses_status
  ON courses (status);

CREATE TABLE IF NOT EXISTS academic_periods (
  id UUID PRIMARY KEY,
  code VARCHAR(40) NOT NULL,
  name VARCHAR(160) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  enrollment_start_date DATE,
  enrollment_end_date DATE,
  status academic_period_status NOT NULL DEFAULT 'PLANNED',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_academic_periods_code UNIQUE (code),
  CONSTRAINT ck_academic_periods_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_academic_periods_enrollment_dates
    CHECK (
      enrollment_start_date IS NULL
      OR enrollment_end_date IS NULL
      OR enrollment_end_date >= enrollment_start_date
    )
);

CREATE INDEX IF NOT EXISTS ix_academic_periods_status
  ON academic_periods (status);

-- ============================================================
-- Academic actors
-- ============================================================

CREATE TABLE IF NOT EXISTS students (
  id UUID PRIMARY KEY,
  person_id UUID NOT NULL,
  academic_program_id UUID NOT NULL,
  code VARCHAR(40) NOT NULL,
  institutional_email VARCHAR(180),
  admission_period VARCHAR(40),
  status student_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_students_person
    FOREIGN KEY (person_id)
    REFERENCES persons (id),

  CONSTRAINT fk_students_academic_program
    FOREIGN KEY (academic_program_id)
    REFERENCES academic_programs (id),

  CONSTRAINT uq_students_person UNIQUE (person_id),
  CONSTRAINT uq_students_code UNIQUE (code),
  CONSTRAINT uq_students_institutional_email UNIQUE (institutional_email)
);

CREATE INDEX IF NOT EXISTS ix_students_academic_program_id
  ON students (academic_program_id);

CREATE INDEX IF NOT EXISTS ix_students_status
  ON students (status);

CREATE TABLE IF NOT EXISTS professors (
  id UUID PRIMARY KEY,
  person_id UUID NOT NULL,
  code VARCHAR(40) NOT NULL,
  institutional_email VARCHAR(180),
  department VARCHAR(180),
  specialty VARCHAR(180),
  status professor_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_professors_person
    FOREIGN KEY (person_id)
    REFERENCES persons (id),

  CONSTRAINT uq_professors_person UNIQUE (person_id),
  CONSTRAINT uq_professors_code UNIQUE (code),
  CONSTRAINT uq_professors_institutional_email UNIQUE (institutional_email)
);

CREATE INDEX IF NOT EXISTS ix_professors_status
  ON professors (status);

-- ============================================================
-- Access and security
-- ============================================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  person_id UUID,
  email VARCHAR(180) NOT NULL,
  password_hash TEXT NOT NULL,
  status user_status NOT NULL DEFAULT 'ACTIVE',
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_users_person
    FOREIGN KEY (person_id)
    REFERENCES persons (id),

  CONSTRAINT uq_users_person UNIQUE (person_id),
  CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE INDEX IF NOT EXISTS ix_users_status
  ON users (status);

CREATE TABLE IF NOT EXISTS roles (
  id UUID PRIMARY KEY,
  code VARCHAR(60) NOT NULL,
  name VARCHAR(120) NOT NULL,
  description TEXT,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  status record_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_roles_code UNIQUE (code),
  CONSTRAINT uq_roles_name UNIQUE (name)
);

CREATE INDEX IF NOT EXISTS ix_roles_status
  ON roles (status);

CREATE TABLE IF NOT EXISTS permissions (
  id UUID PRIMARY KEY,
  code VARCHAR(120) NOT NULL,
  name VARCHAR(160) NOT NULL,
  description TEXT,
  module VARCHAR(80) NOT NULL,
  is_system BOOLEAN NOT NULL DEFAULT FALSE,
  status record_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT uq_permissions_code UNIQUE (code)
);

CREATE INDEX IF NOT EXISTS ix_permissions_module
  ON permissions (module);

CREATE INDEX IF NOT EXISTS ix_permissions_status
  ON permissions (status);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id UUID NOT NULL,
  role_id UUID NOT NULL,
  assigned_by_user_id UUID,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id),

  CONSTRAINT fk_user_roles_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role_id)
    REFERENCES roles (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_user_roles_assigned_by_user
    FOREIGN KEY (assigned_by_user_id)
    REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS ix_user_roles_role_id
  ON user_roles (role_id);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id UUID NOT NULL,
  permission_id UUID NOT NULL,
  assigned_by_user_id UUID,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),

  CONSTRAINT fk_role_permissions_role
    FOREIGN KEY (role_id)
    REFERENCES roles (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_role_permissions_permission
    FOREIGN KEY (permission_id)
    REFERENCES permissions (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_role_permissions_assigned_by_user
    FOREIGN KEY (assigned_by_user_id)
    REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS ix_role_permissions_permission_id
  ON role_permissions (permission_id);

CREATE TABLE IF NOT EXISTS user_sessions (
  id UUID PRIMARY KEY,
  user_id UUID NOT NULL,
  refresh_token_hash TEXT,
  access_token_jti VARCHAR(160),
  device_name VARCHAR(160),
  ip_address VARCHAR(80),
  user_agent TEXT,
  status session_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,

  CONSTRAINT fk_user_sessions_user
    FOREIGN KEY (user_id)
    REFERENCES users (id)
    ON DELETE CASCADE,

  CONSTRAINT uq_user_sessions_access_token_jti UNIQUE (access_token_jti),
  CONSTRAINT ck_user_sessions_dates CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS ix_user_sessions_user_id
  ON user_sessions (user_id);

CREATE INDEX IF NOT EXISTS ix_user_sessions_status
  ON user_sessions (status);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_sessions_one_active_per_user
  ON user_sessions (user_id)
  WHERE status = 'ACTIVE';

-- ============================================================
-- Course offerings and enrollments
-- ============================================================

CREATE TABLE IF NOT EXISTS course_offerings (
  id UUID PRIMARY KEY,
  course_id UUID NOT NULL,
  academic_period_id UUID NOT NULL,
  professor_id UUID,
  section VARCHAR(30) NOT NULL,
  max_capacity INTEGER NOT NULL,
  available_capacity INTEGER,
  status course_offering_status NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_course_offerings_course
    FOREIGN KEY (course_id)
    REFERENCES courses (id),

  CONSTRAINT fk_course_offerings_academic_period
    FOREIGN KEY (academic_period_id)
    REFERENCES academic_periods (id),

  CONSTRAINT fk_course_offerings_professor
    FOREIGN KEY (professor_id)
    REFERENCES professors (id),

  CONSTRAINT uq_course_offerings_course_period_section
    UNIQUE (course_id, academic_period_id, section),

  CONSTRAINT ck_course_offerings_max_capacity_positive
    CHECK (max_capacity > 0),

  CONSTRAINT ck_course_offerings_available_capacity_non_negative
    CHECK (available_capacity IS NULL OR available_capacity >= 0)
);

CREATE INDEX IF NOT EXISTS ix_course_offerings_course_id
  ON course_offerings (course_id);

CREATE INDEX IF NOT EXISTS ix_course_offerings_academic_period_id
  ON course_offerings (academic_period_id);

CREATE INDEX IF NOT EXISTS ix_course_offerings_professor_id
  ON course_offerings (professor_id);

CREATE INDEX IF NOT EXISTS ix_course_offerings_status
  ON course_offerings (status);

CREATE TABLE IF NOT EXISTS enrollments (
  id UUID PRIMARY KEY,
  student_id UUID NOT NULL,
  course_offering_id UUID NOT NULL,
  status enrollment_status NOT NULL DEFAULT 'ENROLLED',
  enrolled_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  registered_by_user_id UUID,
  status_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,

  CONSTRAINT fk_enrollments_student
    FOREIGN KEY (student_id)
    REFERENCES students (id),

  CONSTRAINT fk_enrollments_course_offering
    FOREIGN KEY (course_offering_id)
    REFERENCES course_offerings (id),

  CONSTRAINT fk_enrollments_registered_by_user
    FOREIGN KEY (registered_by_user_id)
    REFERENCES users (id),

  CONSTRAINT uq_enrollments_student_offering
    UNIQUE (student_id, course_offering_id)
);

CREATE INDEX IF NOT EXISTS ix_enrollments_student_id
  ON enrollments (student_id);

CREATE INDEX IF NOT EXISTS ix_enrollments_course_offering_id
  ON enrollments (course_offering_id);

CREATE INDEX IF NOT EXISTS ix_enrollments_status
  ON enrollments (status);

CREATE TABLE IF NOT EXISTS enrollment_status_logs (
  id UUID PRIMARY KEY,
  enrollment_id UUID NOT NULL,
  previous_status enrollment_status,
  new_status enrollment_status NOT NULL,
  reason TEXT,
  changed_by_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_enrollment_status_logs_enrollment
    FOREIGN KEY (enrollment_id)
    REFERENCES enrollments (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_enrollment_status_logs_changed_by_user
    FOREIGN KEY (changed_by_user_id)
    REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS ix_enrollment_status_logs_enrollment_id
  ON enrollment_status_logs (enrollment_id);

CREATE INDEX IF NOT EXISTS ix_enrollment_status_logs_created_at
  ON enrollment_status_logs (created_at);

-- ============================================================
-- Audit
-- ============================================================

CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY,
  actor_user_id UUID,
  action VARCHAR(120) NOT NULL,
  resource_type VARCHAR(120) NOT NULL,
  resource_id VARCHAR(120),
  module VARCHAR(80),
  description TEXT,
  metadata JSONB,
  ip_address VARCHAR(80),
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_audit_logs_actor_user
    FOREIGN KEY (actor_user_id)
    REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS ix_audit_logs_actor_user_id
  ON audit_logs (actor_user_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_resource
  ON audit_logs (resource_type, resource_id);

CREATE INDEX IF NOT EXISTS ix_audit_logs_module
  ON audit_logs (module);

CREATE INDEX IF NOT EXISTS ix_audit_logs_created_at
  ON audit_logs (created_at);

-- ============================================================
-- Student imports
-- ============================================================

CREATE TABLE IF NOT EXISTS student_imports (
  id UUID PRIMARY KEY,
  file_name VARCHAR(255) NOT NULL,
  file_size BIGINT,
  file_mime_type VARCHAR(120),
  status import_status NOT NULL DEFAULT 'PENDING',
  total_rows INTEGER NOT NULL DEFAULT 0,
  processed_rows INTEGER NOT NULL DEFAULT 0,
  accepted_rows INTEGER NOT NULL DEFAULT 0,
  rejected_rows INTEGER NOT NULL DEFAULT 0,
  duplicated_rows INTEGER NOT NULL DEFAULT 0,
  observed_rows INTEGER NOT NULL DEFAULT 0,
  created_by_user_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,

  CONSTRAINT fk_student_imports_created_by_user
    FOREIGN KEY (created_by_user_id)
    REFERENCES users (id),

  CONSTRAINT ck_student_imports_file_size_positive
    CHECK (file_size IS NULL OR file_size >= 0),

  CONSTRAINT ck_student_imports_counts_non_negative
    CHECK (
      total_rows >= 0
      AND processed_rows >= 0
      AND accepted_rows >= 0
      AND rejected_rows >= 0
      AND duplicated_rows >= 0
      AND observed_rows >= 0
    )
);

CREATE INDEX IF NOT EXISTS ix_student_imports_created_by_user_id
  ON student_imports (created_by_user_id);

CREATE INDEX IF NOT EXISTS ix_student_imports_status
  ON student_imports (status);

CREATE INDEX IF NOT EXISTS ix_student_imports_created_at
  ON student_imports (created_at);

CREATE TABLE IF NOT EXISTS student_import_rows (
  id UUID PRIMARY KEY,
  student_import_id UUID NOT NULL,
  row_number INTEGER NOT NULL,
  raw_data JSONB NOT NULL,
  normalized_data JSONB,
  status import_row_status NOT NULL,
  error_summary TEXT,
  field_errors JSONB,
  created_student_id UUID,
  updated_student_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT fk_student_import_rows_student_import
    FOREIGN KEY (student_import_id)
    REFERENCES student_imports (id)
    ON DELETE CASCADE,

  CONSTRAINT fk_student_import_rows_created_student
    FOREIGN KEY (created_student_id)
    REFERENCES students (id),

  CONSTRAINT fk_student_import_rows_updated_student
    FOREIGN KEY (updated_student_id)
    REFERENCES students (id),

  CONSTRAINT uq_student_import_rows_import_row
    UNIQUE (student_import_id, row_number),

  CONSTRAINT ck_student_import_rows_row_number_positive
    CHECK (row_number > 0)
);

CREATE INDEX IF NOT EXISTS ix_student_import_rows_student_import_id
  ON student_import_rows (student_import_id);

CREATE INDEX IF NOT EXISTS ix_student_import_rows_status
  ON student_import_rows (status);

CREATE INDEX IF NOT EXISTS ix_student_import_rows_created_student_id
  ON student_import_rows (created_student_id);

CREATE INDEX IF NOT EXISTS ix_student_import_rows_updated_student_id
  ON student_import_rows (updated_student_id);
