-- PostgreSQL script for academic_management_db
-- Execute with psql, preferably connected to the default "postgres" database first.
-- Example:
--   psql -U postgres -f script_db.sql

DROP DATABASE IF EXISTS academic_management_db;
CREATE DATABASE academic_management_db
  WITH ENCODING = 'UTF8'
  TEMPLATE = template0;

\connect academic_management_db;

-- ------------------------------------------------------------
-- Enum types
-- ------------------------------------------------------------

CREATE TYPE professor_status AS ENUM (
  'ACTIVE',
  'INACTIVE',
  'ON_LEAVE'
);

CREATE TYPE student_status AS ENUM (
  'ACTIVE',
  'INACTIVE',
  'GRADUATED',
  'WITHDRAWN',
  'SUSPENDED'
);

CREATE TYPE course_offering_status AS ENUM (
  'INACTIVE',
  'ACTIVE',
  'CANCELLED',
  'COMPLETED'
);

CREATE TYPE enrollment_status AS ENUM (
  'ENROLLED',
  'WITHDRAWN',
  'COMPLETED',
  'SUSPENDED'
);

-- ------------------------------------------------------------
-- Utility trigger for updated_at
-- ------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------
-- Tables
-- ------------------------------------------------------------

CREATE TABLE person (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  dni CHAR(8) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  phone CHAR(9),
  birth_date DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_person PRIMARY KEY (id),
  CONSTRAINT uk_person_dni UNIQUE (dni),
  CONSTRAINT uk_person_email UNIQUE (email)
);

CREATE TABLE department (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_department PRIMARY KEY (id),
  CONSTRAINT uk_department_name UNIQUE (name)
);

CREATE TABLE course_category (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_course_category PRIMARY KEY (id),
  CONSTRAINT uk_course_category_name UNIQUE (name)
);

CREATE TABLE academic_period (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(20) NOT NULL,
  year SMALLINT NOT NULL,
  semester SMALLINT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_current BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_academic_period PRIMARY KEY (id),
  CONSTRAINT uk_academic_period_name UNIQUE (name),
  CONSTRAINT uk_academic_period_year_semester UNIQUE (year, semester),
  CONSTRAINT chk_academic_period_semester CHECK (semester IN (1, 2)),
  CONSTRAINT chk_academic_period_dates CHECK (end_date > start_date)
);

CREATE TABLE career (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  department_id INTEGER NOT NULL,
  name VARCHAR(150) NOT NULL,
  total_credits SMALLINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_career PRIMARY KEY (id),
  CONSTRAINT uk_career_name UNIQUE (name),
  CONSTRAINT chk_career_total_credits CHECK (total_credits > 0),
  CONSTRAINT fk_career_department
    FOREIGN KEY (department_id) REFERENCES department (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_career_department_id ON career (department_id);

CREATE TABLE professor (
  person_id INTEGER NOT NULL,
  department_id INTEGER,
  code VARCHAR(20) NOT NULL,
  specialty VARCHAR(100),
  institutional_email VARCHAR(150),
  hire_date DATE,
  status professor_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_professor PRIMARY KEY (person_id),
  CONSTRAINT uk_professor_code UNIQUE (code),
  CONSTRAINT uk_professor_institutional_email UNIQUE (institutional_email),
  CONSTRAINT fk_professor_person
    FOREIGN KEY (person_id) REFERENCES person (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_professor_department
    FOREIGN KEY (department_id) REFERENCES department (id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_professor_department_id ON professor (department_id);

CREATE TABLE student (
  person_id INTEGER NOT NULL,
  career_id INTEGER NOT NULL,
  code CHAR(10) NOT NULL,
  institutional_email VARCHAR(150),
  enrollment_date DATE NOT NULL,
  status student_status NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_student PRIMARY KEY (person_id),
  CONSTRAINT uk_student_code UNIQUE (code),
  CONSTRAINT uk_student_institutional_email UNIQUE (institutional_email),
  CONSTRAINT fk_student_person
    FOREIGN KEY (person_id) REFERENCES person (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_student_career
    FOREIGN KEY (career_id) REFERENCES career (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_student_career_id ON student (career_id);

CREATE TABLE course (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  career_id INTEGER NOT NULL,
  category_id INTEGER,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  credits SMALLINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_course PRIMARY KEY (id),
  CONSTRAINT uk_course_career_name UNIQUE (career_id, name),
  CONSTRAINT chk_course_credits CHECK (credits > 0),
  CONSTRAINT fk_course_career
    FOREIGN KEY (career_id) REFERENCES career (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_course_category
    FOREIGN KEY (category_id) REFERENCES course_category (id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_course_career_id ON course (career_id);
CREATE INDEX idx_course_category_id ON course (category_id);

CREATE TABLE course_offering (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  course_id INTEGER NOT NULL,
  academic_period_id INTEGER NOT NULL,
  professor_id INTEGER,
  section VARCHAR(10) NOT NULL DEFAULT 'A',
  max_students SMALLINT NOT NULL DEFAULT 30,
  enrollment_deadline DATE,
  status course_offering_status NOT NULL DEFAULT 'INACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  CONSTRAINT pk_course_offering PRIMARY KEY (id),
  CONSTRAINT uk_course_offering_course_period_section UNIQUE (course_id, academic_period_id, section),
  CONSTRAINT chk_course_offering_max_students CHECK (max_students > 0),
  CONSTRAINT fk_course_offering_course
    FOREIGN KEY (course_id) REFERENCES course (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_course_offering_academic_period
    FOREIGN KEY (academic_period_id) REFERENCES academic_period (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_course_offering_professor
    FOREIGN KEY (professor_id) REFERENCES professor (person_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX idx_course_offering_course_id ON course_offering (course_id);
CREATE INDEX idx_course_offering_academic_period_id ON course_offering (academic_period_id);
CREATE INDEX idx_course_offering_professor_id ON course_offering (professor_id);

CREATE TABLE enrollment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  student_id INTEGER NOT NULL,
  course_offering_id INTEGER NOT NULL,
  status enrollment_status NOT NULL DEFAULT 'ENROLLED',
  enrollment_date DATE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP,
  created_by INTEGER,
  CONSTRAINT pk_enrollment PRIMARY KEY (id),
  CONSTRAINT uk_enrollment_student_offering UNIQUE (student_id, course_offering_id),
  CONSTRAINT fk_enrollment_student
    FOREIGN KEY (student_id) REFERENCES student (person_id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_enrollment_course_offering
    FOREIGN KEY (course_offering_id) REFERENCES course_offering (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_enrollment_student_id ON enrollment (student_id);
CREATE INDEX idx_enrollment_course_offering_id ON enrollment (course_offering_id);
CREATE INDEX idx_enrollment_created_by ON enrollment (created_by);

CREATE TABLE enrollment_status_log (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY,
  enrollment_id INTEGER NOT NULL,
  previous_status enrollment_status,
  new_status enrollment_status NOT NULL,
  reason TEXT,
  changed_by INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_enrollment_status_log PRIMARY KEY (id),
  CONSTRAINT fk_enrollment_status_log_enrollment
    FOREIGN KEY (enrollment_id) REFERENCES enrollment (id)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX idx_enrollment_status_log_enrollment_id ON enrollment_status_log (enrollment_id);
CREATE INDEX idx_enrollment_status_log_changed_by ON enrollment_status_log (changed_by);

-- ------------------------------------------------------------
-- updated_at triggers
-- ------------------------------------------------------------

CREATE TRIGGER trg_person_set_updated_at
BEFORE UPDATE ON person
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_department_set_updated_at
BEFORE UPDATE ON department
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_course_category_set_updated_at
BEFORE UPDATE ON course_category
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_academic_period_set_updated_at
BEFORE UPDATE ON academic_period
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_career_set_updated_at
BEFORE UPDATE ON career
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_professor_set_updated_at
BEFORE UPDATE ON professor
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_student_set_updated_at
BEFORE UPDATE ON student
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_course_set_updated_at
BEFORE UPDATE ON course
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_course_offering_set_updated_at
BEFORE UPDATE ON course_offering
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_enrollment_set_updated_at
BEFORE UPDATE ON enrollment
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
